### ISSUE TITLE
Could not connect to the container. Do you have sufficient privileges?          

### ISSUE THREAD

**Issue by mzupan** [kubernetes-ui/container-terminal#1]
I'm getting the following error. Hitting the correct IP server and URI. If I load it via GET request I get the following

```
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "Upgrade request required",
  "reason": "BadRequest",
  "code": 400
}
```

I can issue commands just fine from `kubectl exec`. I'm not using any auth (that I know of) or ssl. I can access exec remotely from my laptop into a cluster in AWS

```
./kubectl --server="10.122.0.20:8080" exec api-ext-blue-1swdd --namespace=api-ext date
Sun Oct 11 14:42:56 UTC 2015
```

Not sure what is going on

**Comment by stefwalter** [comment]
Which kubernetes are you using, does your build contain https://github.com/kubernetes/kubernetes/pull/13885 ?

**Comment by mzupan** [comment]
Thanks.. using 1.0.6 and that is not in there.
