### ISSUE TITLE
term.js no longer maintained

### ISSUE THREAD

**Issue by benjaminapetersen** [kubernetes-ui/container-terminal#12]
Per the readme:  https://github.com/chjj/term.js/

Looks like there is a fork that is being maintained, though.  https://github.com/sourcelair/xterm.js

**Comment by stefwalter** [comment]
Migrating to xterm is a good idea, and something I've been meaning to do. I haven't gotten started though, so if anyone does have a patch it's more than welcome.

**Comment by benjaminapetersen** [comment]
Yeah that might be a big change. I'm intrigued, we will see what time permits!

**Comment by spadgett** [comment]
Fixed by #25
