### ISSUE TITLE
wss with access_token cannot work for k8s web socket

### ISSUE THREAD

**Issue by shouhong** [kubernetes-ui/container-terminal#20]
It seems "wss" protocol cannot work for k8s web socket.

I tried url "wss://<k8s-master-ip>:8080/api/v1/namespaces/kube-system/pods/kube-dns-v11-6l18b/exec?stdout=1&stdin=1&stderr=1&tty=1&container=etcd&command=%2Fbin%2Fsh&command=-i&access_token=<k8s-token>". The error message is "OSStatus error -9847".

If I replace "wss" with "ws"，it works fine!

Is there anything need to be configured on k8s to make "wss" connection work?

**Comment by stefwalter** [comment]
I think you need to configure TLS certificates. There's a guide here:

https://github.com/kelseyhightower/docker-kubernetes-tls-guide

Alternatively the Openshift Origin distribution of kubernetes configures the TLS certificates for you:

https://www.openshift.org/
